// scripts/extract-context.ts

import mysql from 'mysql2/promise';
import fs from 'fs';
import path from 'path';
import { config } from '../src/config/env';

const OUTPUT_DIR = path.resolve('src/context');

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function ensureOutputDir(): void {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

function writeContext(filename: string, content: string): void {
  const filePath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(filePath, content, 'utf-8');
  console.info(`✅ Written: ${filePath}`);
}

function header(title: string): string {
  const now = new Date().toISOString();
  return `# ${title}\n\n> Auto-generated by \`scripts/extract-context.ts\`\n> Last updated: ${now}\n> **Do not edit manually — run \`npm run context:extract\` to regenerate.**\n\n`;
}

// ─────────────────────────────────────────────────────────────────────────────
// DB EXTRACTION
// ─────────────────────────────────────────────────────────────────────────────

async function extractDbSchema(): Promise<void> {
  console.info('\n📦 Extracting DB schema...');

  const dbName = config.db.name;
  if (!dbName) throw new Error('Database name is required in config');

  const conn = await mysql.createConnection({
    host: config.db.host,
    port: config.db.port,
    database: dbName,
    user: config.db.user,
    password: config.db.password,
  });

  try {
    // 1 — Tüm tablolar
    const [tables] = await conn.execute<any[]>(
      `
      SELECT TABLE_NAME, TABLE_ROWS, TABLE_COMMENT
      FROM INFORMATION_SCHEMA.TABLES
      WHERE TABLE_SCHEMA = ?
      AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME
    `,
      [dbName]
    );

    // 2 — Tüm kolonlar
    const [columns] = await conn.execute<any[]>(
      `
      SELECT 
        TABLE_NAME,
        COLUMN_NAME,
        ORDINAL_POSITION,
        COLUMN_DEFAULT,
        IS_NULLABLE,
        DATA_TYPE,
        CHARACTER_MAXIMUM_LENGTH,
        NUMERIC_PRECISION,
        NUMERIC_SCALE,
        COLUMN_TYPE,
        COLUMN_KEY,
        EXTRA,
        COLUMN_COMMENT
      FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = ?
      ORDER BY TABLE_NAME, ORDINAL_POSITION
    `,
      [dbName]
    );

    // 3 — Foreign keys
    const [foreignKeys] = await conn.execute<any[]>(
      `
      SELECT
        kcu.TABLE_NAME,
        kcu.COLUMN_NAME,
        kcu.REFERENCED_TABLE_NAME,
        kcu.REFERENCED_COLUMN_NAME,
        rc.UPDATE_RULE,
        rc.DELETE_RULE
      FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
      JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
        ON rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
        AND rc.CONSTRAINT_SCHEMA = kcu.TABLE_SCHEMA
      WHERE kcu.TABLE_SCHEMA = ?
      AND kcu.REFERENCED_TABLE_NAME IS NOT NULL
      ORDER BY kcu.TABLE_NAME, kcu.COLUMN_NAME
    `,
      [dbName]
    );

    // 4 — Index'ler
    const [indexes] = await conn.execute<any[]>(
      `
      SELECT
        TABLE_NAME,
        INDEX_NAME,
        NON_UNIQUE,
        COLUMN_NAME,
        SEQ_IN_INDEX
      FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = ?
      ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX
    `,
      [dbName]
    );

    // ── Markdown üret ────────────────────────────────────────────────────────

    let md = header('OrangeHRM Database Schema');

    // Table of contents
    md += '## Tables\n\n';
    for (const table of tables) {
      md += `- [${table.TABLE_NAME}](#${table.TABLE_NAME.toLowerCase().replace(/_/g, '-')})\n`;
    }
    md += '\n---\n\n';

    // Group columns by table
    const columnsByTable = new Map<string, any[]>();
    for (const col of columns) {
      if (!columnsByTable.has(col.TABLE_NAME)) columnsByTable.set(col.TABLE_NAME, []);
      columnsByTable.get(col.TABLE_NAME)!.push(col);
    }

    // Group FK by table
    const fkByTable = new Map<string, any[]>();
    for (const fk of foreignKeys) {
      if (!fkByTable.has(fk.TABLE_NAME)) fkByTable.set(fk.TABLE_NAME, []);
      fkByTable.get(fk.TABLE_NAME)!.push(fk);
    }

    // Group indexes by table
    const idxByTable = new Map<string, any[]>();
    for (const idx of indexes) {
      if (!idxByTable.has(idx.TABLE_NAME)) idxByTable.set(idx.TABLE_NAME, []);
      idxByTable.get(idx.TABLE_NAME)!.push(idx);
    }

    // Per-table detail
    for (const table of tables) {
      const tableName = table.TABLE_NAME;
      md += `## ${tableName}\n\n`;

      // Columns
      md += '### Columns\n\n';
      md += '| Column | Type | Nullable | Default | Key | Extra |\n';
      md += '|--------|------|----------|---------|-----|-------|\n';

      const cols = columnsByTable.get(tableName) ?? [];
      for (const col of cols) {
        const nullable = col.IS_NULLABLE === 'YES' ? '✅' : '❌';
        const colDefault = col.COLUMN_DEFAULT ?? '';
        const key = col.COLUMN_KEY || '';
        const extra = col.EXTRA || '';
        md += `| \`${col.COLUMN_NAME}\` | \`${col.COLUMN_TYPE}\` | ${nullable} | ${colDefault} | ${key} | ${extra} |\n`;
      }
      md += '\n';

      // Foreign keys
      const fks = fkByTable.get(tableName);
      if (fks && fks.length > 0) {
        md += '### Foreign Keys\n\n';
        md += '| Column | References | On Update | On Delete |\n';
        md += '|--------|------------|-----------|----------|\n';
        for (const fk of fks) {
          md += `| \`${fk.COLUMN_NAME}\` | \`${fk.REFERENCED_TABLE_NAME}.${fk.REFERENCED_COLUMN_NAME}\` | ${fk.UPDATE_RULE} | ${fk.DELETE_RULE} |\n`;
        }
        md += '\n';
      }

      // Indexes
      const idxs = idxByTable.get(tableName);
      if (idxs && idxs.length > 0) {
        // Group by index name
        const indexGroups = new Map<string, any[]>();
        for (const idx of idxs) {
          if (!indexGroups.has(idx.INDEX_NAME)) indexGroups.set(idx.INDEX_NAME, []);
          indexGroups.get(idx.INDEX_NAME)!.push(idx);
        }

        md += '### Indexes\n\n';
        md += '| Index | Columns | Unique |\n';
        md += '|-------|---------|--------|\n';
        for (const [idxName, idxCols] of indexGroups) {
          const cols = idxCols
            .sort((a, b) => a.SEQ_IN_INDEX - b.SEQ_IN_INDEX)
            .map((i) => `\`${i.COLUMN_NAME}\``)
            .join(', ');
          const unique = idxCols[0].NON_UNIQUE === 0 ? '✅' : '❌';
          md += `| \`${idxName}\` | ${cols} | ${unique} |\n`;
        }
        md += '\n';
      }

      md += '---\n\n';
    }

    writeContext('db-schema.md', md);
  } finally {
    await conn.end();
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// API EXTRACTION
// ─────────────────────────────────────────────────────────────────────────────

import { execSync } from 'child_process';

async function extractApiContracts(): Promise<void> {
  console.info('\n📡 Extracting API contracts from PHP source...');

  // 1 — Container'daki tüm API PHP dosyalarını bul
  const findCmd = `docker exec orangehrm find /var/www/html/src -name "*API.php" -not -path "*/vendor/*" 2>/dev/null`;
  const fileList = execSync(findCmd).toString().trim().split('\n').filter(Boolean);

  console.info(`   Found ${fileList.length} API files`);

  let md = header('OrangeHRM API Contracts');
  md += '## Overview\n\n';
  md += '> Extracted from PHP OpenAPI annotations in the OrangeHRM source code.\n\n';
  md += '### Base URL\n\n';
  md += '```\nhttp://localhost:8080/web/index.php/api/v2\n```\n\n';
  md += '### Authentication\n\n';
  md += '> Cookie-based session auth. Login via UI, inject `_orangehrm` cookie into API requests.\n\n';
  md += '---\n\n';

  // 2 — Her dosyayı parse et
  const endpoints: ParsedEndpoint[] = [];

  for (const filePath of fileList) {
    try {
      const content = execSync(`docker exec orangehrm cat "${filePath}" 2>/dev/null`).toString();
      const parsed = parseApiFile(filePath, content);
      endpoints.push(...parsed);
    } catch {
      // dosya okunamazsa atla
    }
  }

  // 3 — Plugin'e göre grupla
  const byPlugin = new Map<string, ParsedEndpoint[]>();
  for (const ep of endpoints) {
    if (!byPlugin.has(ep.plugin)) byPlugin.set(ep.plugin, []);
    byPlugin.get(ep.plugin)!.push(ep);
  }

  // 4 — Markdown üret
  for (const [plugin, eps] of [...byPlugin.entries()].sort()) {
    md += `## ${plugin}\n\n`;

    for (const ep of eps) {
      md += `### ${ep.method} ${ep.path}\n\n`;
      if (ep.summary) md += `**Summary:** ${ep.summary}\n\n`;

      if (ep.requestFields.length > 0) {
        md += '**Request Body:**\n\n';
        md += '| Field | Type | Required | Max Length | Notes |\n';
        md += '|-------|------|----------|------------|-------|\n';
        for (const f of ep.requestFields) {
          md += `| \`${f.name}\` | \`${f.type}\` | ${f.required ? '✅' : '❌'} | ${f.maxLength ?? '-'} | ${f.notes ?? ''} |\n`;
        }
        md += '\n';
      }

      if (ep.responseFields.length > 0) {
        md += '**Response Fields:**\n\n';
        md += '| Field | Type | Notes |\n';
        md += '|-------|------|-------|\n';
        for (const f of ep.responseFields) {
          md += `| \`${f.name}\` | \`${f.type}\` | ${f.notes ?? ''} |\n`;
        }
        md += '\n';
      }

      if (ep.paramRules.length > 0) {
        md += '**Validation Rules:**\n\n';
        for (const rule of ep.paramRules) {
          md += `- \`${rule}\`\n`;
        }
        md += '\n';
      }

      md += '---\n\n';
    }
  }

  writeContext('api-contracts.md', md);
  console.info(`   Parsed ${endpoints.length} endpoints`);
}

// ─────────────────────────────────────────────────────────────────────────────
// PARSER
// ─────────────────────────────────────────────────────────────────────────────

interface ParsedField {
  name: string;
  type: string;
  required?: boolean;
  maxLength?: number;
  notes?: string;
}

interface ParsedEndpoint {
  plugin: string;
  method: string;
  path: string;
  summary: string;
  requestFields: ParsedField[];
  responseFields: ParsedField[];
  paramRules: string[];
}

function parseApiFile(filePath: string, content: string): ParsedEndpoint[] {
  const endpoints: ParsedEndpoint[] = [];

  // Plugin adını path'den çıkar
  const pluginMatch = filePath.match(/plugins\/(\w+)\/Api\//);
  const plugin = pluginMatch ? pluginMatch[1].replace('orangehrm', '').replace('Plugin', '').trim() || 'Core' : 'Unknown';

  // @OA\Get, @OA\Post, @OA\Put, @OA\Delete bloklarını bul
  const methodPattern = /@OA\\(Get|Post|Put|Delete|Patch)\s*\(\s*\n\s*\*\s*path="([^"]+)"/gi;
  let methodMatch;

  while ((methodMatch = methodPattern.exec(content)) !== null) {
    const method = methodMatch[1].toUpperCase();
    const path = methodMatch[2];

    // Summary
    const summaryMatch = content.slice(methodMatch.index).match(/summary="([^"]+)"/);
    const summary = summaryMatch?.[1] ?? '';

    // Request body @OA\Property field'larını çıkar
    const requestFields = parseRequestFields(content, methodMatch.index);
    const responseFields = parseResponseFields(content, methodMatch.index);

    // PARAM_RULE constant'larını çıkar
    const paramRules = parseParamRules(content);

    endpoints.push({ plugin, method, path, summary, requestFields, responseFields, paramRules });
  }

  return endpoints;
}

function parseRequestFields(content: string, startIndex: number): ParsedField[] {
  const fields: ParsedField[] = [];
  const block = content.slice(startIndex, startIndex + 3000);

  // @OA\RequestBody bloğunu bul
  const reqBodyMatch = block.match(/@OA\\RequestBody[\s\S]*?@OA\\Response/);
  if (!reqBodyMatch) return fields;

  const reqBody = reqBodyMatch[0];

  // Her @OA\Property'yi parse et
  const propPattern = /@OA\\Property\s*\(([^)]+)\)/g;
  let propMatch;

  while ((propMatch = propPattern.exec(reqBody)) !== null) {
    const propContent = propMatch[1];

    const nameMatch = propContent.match(/property="([^"]+)"/);
    const typeMatch = propContent.match(/type="([^"]+)"/);
    const maxLenMatch = propContent.match(/maxLength=[\w\\:]+::(\w+)/);

    if (!nameMatch) continue;

    const name = nameMatch[1];
    const type = typeMatch?.[1] ?? 'string';

    // required array'inden kontrol et
    const requiredMatch = reqBody.match(/required=\{([^}]+)\}/);
    const required = requiredMatch ? requiredMatch[1].includes(`"${name}"`) : false;

    fields.push({ name, type, required, maxLength: undefined, notes: '' });
  }

  return fields;
}

function parseResponseFields(content: string, startIndex: number): ParsedField[] {
  // Model dosyasından response field'larını çıkar — ayrı parse
  return [];
}

function parseParamRules(content: string): string[] {
  const rules: string[] = [];
  const rulePattern = /PARAM_RULE_(\w+)\s*=\s*(\d+)/g;
  let match;

  while ((match = rulePattern.exec(content)) !== null) {
    rules.push(`${match[1]}: max ${match[2]} chars`);
  }

  return rules;
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.info('🚀 Context extraction starting...\n');
  ensureOutputDir();

  await extractDbSchema();
  await extractApiContracts();

  // UI extraction — later
  // await extractUiElements();

  console.info('\n✅ Context extraction complete.');
  console.info(`📁 Output: ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error('❌ Context extraction failed:', err);
  process.exit(1);
});
