import fs from 'fs';
import path from 'path';

const AUTO_START = '<!-- AUTO-GENERATED:START -->';
const AUTO_END = '<!-- AUTO-GENERATED:END -->';
const STATE_PATH = path.resolve('PROJECT_STATE.md');

const IGNORE_DIRS = new Set(['node_modules', '.git', 'reports', 'dist', '.next']);

const PURPOSE_HINTS: Record<string, string> = {
  '.spec.ts': 'Test spec',
  '.page.ts': 'Page Object — encapsulates locators/actions for one screen',
  '.util.ts': 'Utility class — shared logic (API, DB, etc.)',
  '.fixture.ts': 'Playwright fixture — dependency injection for tests',
  '.factory.ts': 'Test data factory',
  '.types.ts': 'Shared TypeScript types/interfaces',
};

function inferPurpose(filePath: string): string {
  for (const [suffix, purpose] of Object.entries(PURPOSE_HINTS)) {
    if (filePath.endsWith(suffix)) return purpose;
  }
  return '—';
}

function walk(dir: string, base = dir, lines: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (IGNORE_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, base, lines);
    } else if (entry.name.endsWith('.ts') || entry.name.endsWith('.md')) {
      const rel = path.relative(base, full);
      lines.push(`| \`${rel}\` | ${inferPurpose(rel)} |`);
    }
  }
  return lines;
}

function main(): void {
  const fileLines = ['| File | Purpose |', '|------|---------|', ...walk('src'), ...walk('tests'), ...walk('agents')];
  const autoBlock = `${AUTO_START}\n\n## File Tree & Purpose\n\n> Regenerated by \`npm run docs:state\` — do not edit by hand.\n\n${fileLines.join('\n')}\n\n${AUTO_END}`;

  const existing = fs.existsSync(STATE_PATH) ? fs.readFileSync(STATE_PATH, 'utf-8') : '';
  const startIdx = existing.indexOf(AUTO_START);
  const endIdx = existing.indexOf(AUTO_END);

  const updated =
    startIdx !== -1 && endIdx !== -1
      ? existing.slice(0, startIdx) + autoBlock + existing.slice(endIdx + AUTO_END.length)
      : `${existing}\n\n${autoBlock}\n`;

  fs.writeFileSync(STATE_PATH, updated, 'utf-8');
  console.info('✅ PROJECT_STATE.md auto-section refreshed.');
}

main();